name = infectious
title = Infectious
description = Aggressive apocalyptic zombies that infect all animalia mobs. Immune to sunlight, fast, and deadly.
author = shixian
depends = default, animalia, creatura
min_minetest_version = 5.6.0
